# Generated by Django 5.2.1 on 2025-06-09 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basearq', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
