# Generated by Django 5.2.1 on 2025-06-12 23:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basearq', '0004_arquitecto_ciudad_imagenobra_obra_delete_nuevasobras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagenobra',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='basearq.obra'),
        ),
    ]
